# Generated by Django 4.1.1 on 2022-09-10 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkIngredientRelationshipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_amount', models.FloatField()),
                ('ingredient_unit', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('description', models.CharField(max_length=2300)),
                ('image', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=230)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('completed_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('drink_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gospel_swamp_menu_backend.drinkmodel')),
            ],
        ),
        migrations.AddField(
            model_name='drinkmodel',
            name='ingredients',
            field=models.ManyToManyField(through='gospel_swamp_menu_backend.DrinkIngredientRelationshipModel', to='gospel_swamp_menu_backend.ingredientmodel'),
        ),
        migrations.AddField(
            model_name='drinkingredientrelationshipmodel',
            name='drink_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gospel_swamp_menu_backend.drinkmodel'),
        ),
        migrations.AddField(
            model_name='drinkingredientrelationshipmodel',
            name='ingredient_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gospel_swamp_menu_backend.ingredientmodel'),
        ),
    ]
